// Code generated by MockGen. DO NOT EDIT.
// Source: domain/contracts/voucher_contracts.go

// Package repository_mock is a generated GoMock package.
package repository_mock

import (
	context "context"
	reflect "reflect"

	dto "github.com/BangNopall/hology8-be/domain/dto"
	entity "github.com/BangNopall/hology8-be/domain/entity"
	gomock "github.com/golang/mock/gomock"
	gorm "gorm.io/gorm"
)

// MockVoucherRepository is a mock of VoucherRepository interface.
type MockVoucherRepository struct {
	ctrl     *gomock.Controller
	recorder *MockVoucherRepositoryMockRecorder
}

// MockVoucherRepositoryMockRecorder is the mock recorder for MockVoucherRepository.
type MockVoucherRepositoryMockRecorder struct {
	mock *MockVoucherRepository
}

// NewMockVoucherRepository creates a new mock instance.
func NewMockVoucherRepository(ctrl *gomock.Controller) *MockVoucherRepository {
	mock := &MockVoucherRepository{ctrl: ctrl}
	mock.recorder = &MockVoucherRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockVoucherRepository) EXPECT() *MockVoucherRepositoryMockRecorder {
	return m.recorder
}

// FetchAll mocks base method.
func (m *MockVoucherRepository) FetchAll(ctx context.Context) ([]entity.Voucher, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FetchAll", ctx)
	ret0, _ := ret[0].([]entity.Voucher)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FetchAll indicates an expected call of FetchAll.
func (mr *MockVoucherRepositoryMockRecorder) FetchAll(ctx interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FetchAll", reflect.TypeOf((*MockVoucherRepository)(nil).FetchAll), ctx)
}

// FetchByID mocks base method.
func (m *MockVoucherRepository) FetchByID(ctx context.Context, id string) (entity.Voucher, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FetchByID", ctx, id)
	ret0, _ := ret[0].(entity.Voucher)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FetchByID indicates an expected call of FetchByID.
func (mr *MockVoucherRepositoryMockRecorder) FetchByID(ctx, id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FetchByID", reflect.TypeOf((*MockVoucherRepository)(nil).FetchByID), ctx, id)
}

// InsertVoucher mocks base method.
func (m *MockVoucherRepository) InsertVoucher(ctx context.Context, voucher *entity.Voucher) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "InsertVoucher", ctx, voucher)
	ret0, _ := ret[0].(error)
	return ret0
}

// InsertVoucher indicates an expected call of InsertVoucher.
func (mr *MockVoucherRepositoryMockRecorder) InsertVoucher(ctx, voucher interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "InsertVoucher", reflect.TypeOf((*MockVoucherRepository)(nil).InsertVoucher), ctx, voucher)
}

// UpdateVoucher mocks base method.
func (m *MockVoucherRepository) UpdateVoucher(ctx context.Context, voucher *entity.Voucher, tx *gorm.DB) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateVoucher", ctx, voucher, tx)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateVoucher indicates an expected call of UpdateVoucher.
func (mr *MockVoucherRepositoryMockRecorder) UpdateVoucher(ctx, voucher, tx interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateVoucher", reflect.TypeOf((*MockVoucherRepository)(nil).UpdateVoucher), ctx, voucher, tx)
}

// MockVoucherService is a mock of VoucherService interface.
type MockVoucherService struct {
	ctrl     *gomock.Controller
	recorder *MockVoucherServiceMockRecorder
}

// MockVoucherServiceMockRecorder is the mock recorder for MockVoucherService.
type MockVoucherServiceMockRecorder struct {
	mock *MockVoucherService
}

// NewMockVoucherService creates a new mock instance.
func NewMockVoucherService(ctrl *gomock.Controller) *MockVoucherService {
	mock := &MockVoucherService{ctrl: ctrl}
	mock.recorder = &MockVoucherServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockVoucherService) EXPECT() *MockVoucherServiceMockRecorder {
	return m.recorder
}

// FetchAll mocks base method.
func (m *MockVoucherService) FetchAll(ctx context.Context) ([]dto.VoucherResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FetchAll", ctx)
	ret0, _ := ret[0].([]dto.VoucherResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FetchAll indicates an expected call of FetchAll.
func (mr *MockVoucherServiceMockRecorder) FetchAll(ctx interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FetchAll", reflect.TypeOf((*MockVoucherService)(nil).FetchAll), ctx)
}

// FetchByID mocks base method.
func (m *MockVoucherService) FetchByID(ctx context.Context, id string) (dto.VoucherResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FetchByID", ctx, id)
	ret0, _ := ret[0].(dto.VoucherResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FetchByID indicates an expected call of FetchByID.
func (mr *MockVoucherServiceMockRecorder) FetchByID(ctx, id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FetchByID", reflect.TypeOf((*MockVoucherService)(nil).FetchByID), ctx, id)
}

// InsertVoucher mocks base method.
func (m *MockVoucherService) InsertVoucher(ctx context.Context, voucher *dto.VoucherRequest) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "InsertVoucher", ctx, voucher)
	ret0, _ := ret[0].(error)
	return ret0
}

// InsertVoucher indicates an expected call of InsertVoucher.
func (mr *MockVoucherServiceMockRecorder) InsertVoucher(ctx, voucher interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "InsertVoucher", reflect.TypeOf((*MockVoucherService)(nil).InsertVoucher), ctx, voucher)
}

// RedeemVoucher mocks base method.
func (m *MockVoucherService) RedeemVoucher(ctx context.Context, voucher *dto.VoucherRedeem) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RedeemVoucher", ctx, voucher)
	ret0, _ := ret[0].(error)
	return ret0
}

// RedeemVoucher indicates an expected call of RedeemVoucher.
func (mr *MockVoucherServiceMockRecorder) RedeemVoucher(ctx, voucher interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RedeemVoucher", reflect.TypeOf((*MockVoucherService)(nil).RedeemVoucher), ctx, voucher)
}
