// Code generated by MockGen. DO NOT EDIT.
// Source: C:\Users\ASUS.LAPTOP-NQO5FA1P\NGODING\Golang\hology-be\pkg\gomail\gomail.go

// Package mock_gomail is a generated GoMock package.
package mock_gomail

import (
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockGoMailInterface is a mock of GoMailInterface interface.
type MockGoMailInterface struct {
	ctrl     *gomock.Controller
	recorder *MockGoMailInterfaceMockRecorder
}

// MockGoMailInterfaceMockRecorder is the mock recorder for MockGoMailInterface.
type MockGoMailInterfaceMockRecorder struct {
	mock *MockGoMailInterface
}

// NewMockGoMailInterface creates a new mock instance.
func NewMockGoMailInterface(ctrl *gomock.Controller) *MockGoMailInterface {
	mock := &MockGoMailInterface{ctrl: ctrl}
	mock.recorder = &MockGoMailInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockGoMailInterface) EXPECT() *MockGoMailInterfaceMockRecorder {
	return m.recorder
}

// SendEmail mocks base method.
func (m *MockGoMailInterface) SendEmail(subject, htmlBody, email string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SendEmail", subject, htmlBody, email)
	ret0, _ := ret[0].(error)
	return ret0
}

// SendEmail indicates an expected call of SendEmail.
func (mr *MockGoMailInterfaceMockRecorder) SendEmail(subject, htmlBody, email interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SendEmail", reflect.TypeOf((*MockGoMailInterface)(nil).SendEmail), subject, htmlBody, email)
}

// SendEmails mocks base method.
func (m *MockGoMailInterface) SendEmails(subject, htmlBody string, emails []string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SendEmails", subject, htmlBody, emails)
	ret0, _ := ret[0].(error)
	return ret0
}

// SendEmails indicates an expected call of SendEmails.
func (mr *MockGoMailInterfaceMockRecorder) SendEmails(subject, htmlBody, emails interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SendEmails", reflect.TypeOf((*MockGoMailInterface)(nil).SendEmails), subject, htmlBody, emails)
}
