// Code generated by MockGen. DO NOT EDIT.
// Source: domain/contracts/competition_contracts.go

// Package repository_mock is a generated GoMock package.
package repository_mock

import (
	context "context"
	reflect "reflect"

	entity "github.com/BangNopall/hology8-be/domain/entity"
	gomock "github.com/golang/mock/gomock"
)

// MockCompetitionRepository is a mock of CompetitionRepository interface.
type MockCompetitionRepository struct {
	ctrl     *gomock.Controller
	recorder *MockCompetitionRepositoryMockRecorder
}

// MockCompetitionRepositoryMockRecorder is the mock recorder for MockCompetitionRepository.
type MockCompetitionRepositoryMockRecorder struct {
	mock *MockCompetitionRepository
}

// NewMockCompetitionRepository creates a new mock instance.
func NewMockCompetitionRepository(ctrl *gomock.Controller) *MockCompetitionRepository {
	mock := &MockCompetitionRepository{ctrl: ctrl}
	mock.recorder = &MockCompetitionRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockCompetitionRepository) EXPECT() *MockCompetitionRepositoryMockRecorder {
	return m.recorder
}

// DeleteCompe mocks base method.
func (m *MockCompetitionRepository) DeleteCompe(ctx context.Context, id int) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteCompe", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteCompe indicates an expected call of DeleteCompe.
func (mr *MockCompetitionRepositoryMockRecorder) DeleteCompe(ctx, id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteCompe", reflect.TypeOf((*MockCompetitionRepository)(nil).DeleteCompe), ctx, id)
}

// FetchAll mocks base method.
func (m *MockCompetitionRepository) FetchAll(ctx context.Context) ([]entity.Competition, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FetchAll", ctx)
	ret0, _ := ret[0].([]entity.Competition)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FetchAll indicates an expected call of FetchAll.
func (mr *MockCompetitionRepositoryMockRecorder) FetchAll(ctx interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FetchAll", reflect.TypeOf((*MockCompetitionRepository)(nil).FetchAll), ctx)
}

// FetchAllByConditionAndRelation mocks base method.
func (m *MockCompetitionRepository) FetchAllByConditionAndRelation(ctx context.Context, condition string, args []interface{}, preload ...string) ([]entity.Competition, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{ctx, condition, args}
	for _, a := range preload {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "FetchAllByConditionAndRelation", varargs...)
	ret0, _ := ret[0].([]entity.Competition)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FetchAllByConditionAndRelation indicates an expected call of FetchAllByConditionAndRelation.
func (mr *MockCompetitionRepositoryMockRecorder) FetchAllByConditionAndRelation(ctx, condition, args interface{}, preload ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{ctx, condition, args}, preload...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FetchAllByConditionAndRelation", reflect.TypeOf((*MockCompetitionRepository)(nil).FetchAllByConditionAndRelation), varargs...)
}

// FetchOneByID mocks base method.
func (m *MockCompetitionRepository) FetchOneByID(ctx context.Context, id int) (entity.Competition, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FetchOneByID", ctx, id)
	ret0, _ := ret[0].(entity.Competition)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FetchOneByID indicates an expected call of FetchOneByID.
func (mr *MockCompetitionRepositoryMockRecorder) FetchOneByID(ctx, id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FetchOneByID", reflect.TypeOf((*MockCompetitionRepository)(nil).FetchOneByID), ctx, id)
}

// FetchOneWithRelations mocks base method.
func (m *MockCompetitionRepository) FetchOneWithRelations(ctx context.Context, id int, relations ...string) (entity.Competition, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{ctx, id}
	for _, a := range relations {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "FetchOneWithRelations", varargs...)
	ret0, _ := ret[0].(entity.Competition)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FetchOneWithRelations indicates an expected call of FetchOneWithRelations.
func (mr *MockCompetitionRepositoryMockRecorder) FetchOneWithRelations(ctx, id interface{}, relations ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{ctx, id}, relations...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FetchOneWithRelations", reflect.TypeOf((*MockCompetitionRepository)(nil).FetchOneWithRelations), varargs...)
}

// InsertCompe mocks base method.
func (m *MockCompetitionRepository) InsertCompe(ctx context.Context, compe *entity.Competition) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "InsertCompe", ctx, compe)
	ret0, _ := ret[0].(error)
	return ret0
}

// InsertCompe indicates an expected call of InsertCompe.
func (mr *MockCompetitionRepositoryMockRecorder) InsertCompe(ctx, compe interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "InsertCompe", reflect.TypeOf((*MockCompetitionRepository)(nil).InsertCompe), ctx, compe)
}

// UpdateCompe mocks base method.
func (m *MockCompetitionRepository) UpdateCompe(ctx context.Context, compe *entity.Competition) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateCompe", ctx, compe)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateCompe indicates an expected call of UpdateCompe.
func (mr *MockCompetitionRepositoryMockRecorder) UpdateCompe(ctx, compe interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateCompe", reflect.TypeOf((*MockCompetitionRepository)(nil).UpdateCompe), ctx, compe)
}
