// Code generated by MockGen. DO NOT EDIT.
// Source: domain/contracts/user_contracts.go

// Package repository_mock is a generated GoMock package.
package repository_mock

import (
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	uuid "github.com/google/uuid"
	dto "github.com/hology8/hology-be/domain/dto"
	entity "github.com/hology8/hology-be/domain/entity"
)

// MockUserRepository is a mock of UserRepository interface.
type MockUserRepository struct {
	ctrl     *gomock.Controller
	recorder *MockUserRepositoryMockRecorder
}

// MockUserRepositoryMockRecorder is the mock recorder for MockUserRepository.
type MockUserRepositoryMockRecorder struct {
	mock *MockUserRepository
}

// NewMockUserRepository creates a new mock instance.
func NewMockUserRepository(ctrl *gomock.Controller) *MockUserRepository {
	mock := &MockUserRepository{ctrl: ctrl}
	mock.recorder = &MockUserRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockUserRepository) EXPECT() *MockUserRepositoryMockRecorder {
	return m.recorder
}

// CreateUser mocks base method.
func (m *MockUserRepository) CreateUser(user *entity.User) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateUser", user)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateUser indicates an expected call of CreateUser.
func (mr *MockUserRepositoryMockRecorder) CreateUser(user interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateUser", reflect.TypeOf((*MockUserRepository)(nil).CreateUser), user)
}

// DeleteUnverifiedUser mocks base method.
func (m *MockUserRepository) DeleteUnverifiedUser() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteUnverifiedUser")
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteUnverifiedUser indicates an expected call of DeleteUnverifiedUser.
func (mr *MockUserRepositoryMockRecorder) DeleteUnverifiedUser() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteUnverifiedUser", reflect.TypeOf((*MockUserRepository)(nil).DeleteUnverifiedUser))
}

// FetchAllByConditionAndRelation mocks base method.
func (m *MockUserRepository) FetchAllByConditionAndRelation(condition string, args []interface{}, joins []string, pageParam *dto.PaginationRequest, preload ...string) ([]entity.User, dto.PaginationResponse, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{condition, args, joins, pageParam}
	for _, a := range preload {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "FetchAllByConditionAndRelation", varargs...)
	ret0, _ := ret[0].([]entity.User)
	ret1, _ := ret[1].(dto.PaginationResponse)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// FetchAllByConditionAndRelation indicates an expected call of FetchAllByConditionAndRelation.
func (mr *MockUserRepositoryMockRecorder) FetchAllByConditionAndRelation(condition, args, joins, pageParam interface{}, preload ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{condition, args, joins, pageParam}, preload...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FetchAllByConditionAndRelation", reflect.TypeOf((*MockUserRepository)(nil).FetchAllByConditionAndRelation), varargs...)
}

// FindUser mocks base method.
func (m *MockUserRepository) FindUser(user *entity.User, userParam *dto.UserParam, relations ...string) error {
	m.ctrl.T.Helper()
	varargs := []interface{}{user, userParam}
	for _, a := range relations {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "FindUser", varargs...)
	ret0, _ := ret[0].(error)
	return ret0
}

// FindUser indicates an expected call of FindUser.
func (mr *MockUserRepositoryMockRecorder) FindUser(user, userParam interface{}, relations ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{user, userParam}, relations...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindUser", reflect.TypeOf((*MockUserRepository)(nil).FindUser), varargs...)
}

// UpdateUser mocks base method.
func (m *MockUserRepository) UpdateUser(updateUser *dto.UserUpdate, userId uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateUser", updateUser, userId)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateUser indicates an expected call of UpdateUser.
func (mr *MockUserRepositoryMockRecorder) UpdateUser(updateUser, userId interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateUser", reflect.TypeOf((*MockUserRepository)(nil).UpdateUser), updateUser, userId)
}
