// Code generated by MockGen. DO NOT EDIT.
// Source: C:\Users\ASUS.LAPTOP-NQO5FA1P\NGODING\Golang\hology-be\internal\app\admin\repository\admin_repository.go

// Package mock_repository is a generated GoMock package.
package mock_repository

import (
	reflect "reflect"

	dto "github.com/BangNopall/hology8-be/domain/dto"
	entity "github.com/BangNopall/hology8-be/domain/entity"
	gomock "github.com/golang/mock/gomock"
)

// MockAdminRepository is a mock of AdminRepository interface.
type MockAdminRepository struct {
	ctrl     *gomock.Controller
	recorder *MockAdminRepositoryMockRecorder
}

// MockAdminRepositoryMockRecorder is the mock recorder for MockAdminRepository.
type MockAdminRepositoryMockRecorder struct {
	mock *MockAdminRepository
}

// NewMockAdminRepository creates a new mock instance.
func NewMockAdminRepository(ctrl *gomock.Controller) *MockAdminRepository {
	mock := &MockAdminRepository{ctrl: ctrl}
	mock.recorder = &MockAdminRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAdminRepository) EXPECT() *MockAdminRepositoryMockRecorder {
	return m.recorder
}

// FindAdmin mocks base method.
func (m *MockAdminRepository) FindAdmin(admin *entity.Admin, adminParam *dto.AdminParam) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindAdmin", admin, adminParam)
	ret0, _ := ret[0].(error)
	return ret0
}

// FindAdmin indicates an expected call of FindAdmin.
func (mr *MockAdminRepositoryMockRecorder) FindAdmin(admin, adminParam interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindAdmin", reflect.TypeOf((*MockAdminRepository)(nil).FindAdmin), admin, adminParam)
}
