// Code generated by MockGen. DO NOT EDIT.
// Source: domain/contracts/university_contracts.go

// Package repository_mock is a generated GoMock package.
package repository_mock

import (
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	dto "github.com/hology8/hology-be/domain/dto"
	entity "github.com/hology8/hology-be/domain/entity"
)

// MockUniversityRepository is a mock of UniversityRepository interface.
type MockUniversityRepository struct {
	ctrl     *gomock.Controller
	recorder *MockUniversityRepositoryMockRecorder
}

// MockUniversityRepositoryMockRecorder is the mock recorder for MockUniversityRepository.
type MockUniversityRepositoryMockRecorder struct {
	mock *MockUniversityRepository
}

// NewMockUniversityRepository creates a new mock instance.
func NewMockUniversityRepository(ctrl *gomock.Controller) *MockUniversityRepository {
	mock := &MockUniversityRepository{ctrl: ctrl}
	mock.recorder = &MockUniversityRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockUniversityRepository) EXPECT() *MockUniversityRepositoryMockRecorder {
	return m.recorder
}

// FetchAll mocks base method.
func (m *MockUniversityRepository) FetchAll(ctx context.Context, params *dto.UniversityParam) ([]entity.University, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FetchAll", ctx, params)
	ret0, _ := ret[0].([]entity.University)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FetchAll indicates an expected call of FetchAll.
func (mr *MockUniversityRepositoryMockRecorder) FetchAll(ctx, params interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FetchAll", reflect.TypeOf((*MockUniversityRepository)(nil).FetchAll), ctx, params)
}

// FetchByID mocks base method.
func (m *MockUniversityRepository) FetchByID(ctx context.Context, id int) (entity.University, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FetchByID", ctx, id)
	ret0, _ := ret[0].(entity.University)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FetchByID indicates an expected call of FetchByID.
func (mr *MockUniversityRepositoryMockRecorder) FetchByID(ctx, id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FetchByID", reflect.TypeOf((*MockUniversityRepository)(nil).FetchByID), ctx, id)
}
