// Code generated by MockGen. DO NOT EDIT.
// Source: pkg/firebase/firebase.go

// Package mock is a generated GoMock package.
package mock

import (
	multipart "mime/multipart"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockFirebaseStorage is a mock of FirebaseStorage interface.
type MockFirebaseStorage struct {
	ctrl     *gomock.Controller
	recorder *MockFirebaseStorageMockRecorder
}

// MockFirebaseStorageMockRecorder is the mock recorder for MockFirebaseStorage.
type MockFirebaseStorageMockRecorder struct {
	mock *MockFirebaseStorage
}

// NewMockFirebaseStorage creates a new mock instance.
func NewMockFirebaseStorage(ctrl *gomock.Controller) *MockFirebaseStorage {
	mock := &MockFirebaseStorage{ctrl: ctrl}
	mock.recorder = &MockFirebaseStorageMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockFirebaseStorage) EXPECT() *MockFirebaseStorageMockRecorder {
	return m.recorder
}

// Delete mocks base method.
func (m *MockFirebaseStorage) Delete(relativePath string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", relativePath)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockFirebaseStorageMockRecorder) Delete(relativePath interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockFirebaseStorage)(nil).Delete), relativePath)
}

// Update mocks base method.
func (m *MockFirebaseStorage) Update(relativePath string, file *multipart.FileHeader, oldUrl string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", relativePath, file, oldUrl)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Update indicates an expected call of Update.
func (mr *MockFirebaseStorageMockRecorder) Update(relativePath, file, oldUrl interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockFirebaseStorage)(nil).Update), relativePath, file, oldUrl)
}

// Upload mocks base method.
func (m *MockFirebaseStorage) Upload(relativePath string, file *multipart.FileHeader) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Upload", relativePath, file)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Upload indicates an expected call of Upload.
func (mr *MockFirebaseStorageMockRecorder) Upload(relativePath, file interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Upload", reflect.TypeOf((*MockFirebaseStorage)(nil).Upload), relativePath, file)
}
