// Code generated by MockGen. DO NOT EDIT.
// Source: domain/contracts/province_contracts.go

// Package repository_mock is a generated GoMock package.
package repository_mock

import (
	context "context"
	reflect "reflect"

	entity "github.com/BangNopall/hology8-be/domain/entity"
	gomock "github.com/golang/mock/gomock"
)

// MockProvinceRepository is a mock of ProvinceRepository interface.
type MockProvinceRepository struct {
	ctrl     *gomock.Controller
	recorder *MockProvinceRepositoryMockRecorder
}

// MockProvinceRepositoryMockRecorder is the mock recorder for MockProvinceRepository.
type MockProvinceRepositoryMockRecorder struct {
	mock *MockProvinceRepository
}

// NewMockProvinceRepository creates a new mock instance.
func NewMockProvinceRepository(ctrl *gomock.Controller) *MockProvinceRepository {
	mock := &MockProvinceRepository{ctrl: ctrl}
	mock.recorder = &MockProvinceRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockProvinceRepository) EXPECT() *MockProvinceRepositoryMockRecorder {
	return m.recorder
}

// FetchAll mocks base method.
func (m *MockProvinceRepository) FetchAll(ctx context.Context) ([]entity.Province, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FetchAll", ctx)
	ret0, _ := ret[0].([]entity.Province)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FetchAll indicates an expected call of FetchAll.
func (mr *MockProvinceRepositoryMockRecorder) FetchAll(ctx interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FetchAll", reflect.TypeOf((*MockProvinceRepository)(nil).FetchAll), ctx)
}

// FetchByID mocks base method.
func (m *MockProvinceRepository) FetchByID(ctx context.Context, id int) (entity.Province, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FetchByID", ctx, id)
	ret0, _ := ret[0].(entity.Province)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FetchByID indicates an expected call of FetchByID.
func (mr *MockProvinceRepositoryMockRecorder) FetchByID(ctx, id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FetchByID", reflect.TypeOf((*MockProvinceRepository)(nil).FetchByID), ctx, id)
}
