// Code generated by MockGen. DO NOT EDIT.
// Source: domain/contracts/log_contracts.go

// Package repository_mock is a generated GoMock package.
package repository_mock

import (
	context "context"
	reflect "reflect"

	entity "github.com/BangNopall/hology8-be/domain/entity"
	gomock "github.com/golang/mock/gomock"
)

// MockLogRepository is a mock of LogRepository interface.
type MockLogRepository struct {
	ctrl     *gomock.Controller
	recorder *MockLogRepositoryMockRecorder
}

// MockLogRepositoryMockRecorder is the mock recorder for MockLogRepository.
type MockLogRepositoryMockRecorder struct {
	mock *MockLogRepository
}

// NewMockLogRepository creates a new mock instance.
func NewMockLogRepository(ctrl *gomock.Controller) *MockLogRepository {
	mock := &MockLogRepository{ctrl: ctrl}
	mock.recorder = &MockLogRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockLogRepository) EXPECT() *MockLogRepositoryMockRecorder {
	return m.recorder
}

// FetchAll mocks base method.
func (m *MockLogRepository) FetchAll(context context.Context, relations ...string) ([]entity.Log, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{context}
	for _, a := range relations {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "FetchAll", varargs...)
	ret0, _ := ret[0].([]entity.Log)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FetchAll indicates an expected call of FetchAll.
func (mr *MockLogRepositoryMockRecorder) FetchAll(context interface{}, relations ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{context}, relations...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FetchAll", reflect.TypeOf((*MockLogRepository)(nil).FetchAll), varargs...)
}

// FetchOneByID mocks base method.
func (m *MockLogRepository) FetchOneByID(context context.Context, id int) (entity.Log, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FetchOneByID", context, id)
	ret0, _ := ret[0].(entity.Log)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FetchOneByID indicates an expected call of FetchOneByID.
func (mr *MockLogRepositoryMockRecorder) FetchOneByID(context, id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FetchOneByID", reflect.TypeOf((*MockLogRepository)(nil).FetchOneByID), context, id)
}

// InsertLog mocks base method.
func (m *MockLogRepository) InsertLog(context context.Context, log *entity.Log) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "InsertLog", context, log)
	ret0, _ := ret[0].(error)
	return ret0
}

// InsertLog indicates an expected call of InsertLog.
func (mr *MockLogRepositoryMockRecorder) InsertLog(context, log interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "InsertLog", reflect.TypeOf((*MockLogRepository)(nil).InsertLog), context, log)
}
