// Code generated by MockGen. DO NOT EDIT.
// Source: ./pkg/aws/s3.go

// Package mock is a generated GoMock package.
package mock

import (
	multipart "mime/multipart"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockCloudStorage is a mock of CloudStorage interface.
type MockCloudStorage struct {
	ctrl     *gomock.Controller
	recorder *MockCloudStorageMockRecorder
}

// MockCloudStorageMockRecorder is the mock recorder for MockCloudStorage.
type MockCloudStorageMockRecorder struct {
	mock *MockCloudStorage
}

// NewMockCloudStorage creates a new mock instance.
func NewMockCloudStorage(ctrl *gomock.Controller) *MockCloudStorage {
	mock := &MockCloudStorage{ctrl: ctrl}
	mock.recorder = &MockCloudStorageMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockCloudStorage) EXPECT() *MockCloudStorageMockRecorder {
	return m.recorder
}

// Delete mocks base method.
func (m *MockCloudStorage) Delete(oldUrl string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", oldUrl)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockCloudStorageMockRecorder) Delete(oldUrl interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockCloudStorage)(nil).Delete), oldUrl)
}

// Update mocks base method.
func (m *MockCloudStorage) Update(relativePath string, file *multipart.FileHeader, oldUrl string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", relativePath, file, oldUrl)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Update indicates an expected call of Update.
func (mr *MockCloudStorageMockRecorder) Update(relativePath, file, oldUrl interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockCloudStorage)(nil).Update), relativePath, file, oldUrl)
}

// Upload mocks base method.
func (m *MockCloudStorage) Upload(relativePath string, file *multipart.FileHeader) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Upload", relativePath, file)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Upload indicates an expected call of Upload.
func (mr *MockCloudStorageMockRecorder) Upload(relativePath, file interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Upload", reflect.TypeOf((*MockCloudStorage)(nil).Upload), relativePath, file)
}
