// Code generated by MockGen. DO NOT EDIT.
// Source: domain/contracts/team_contracts.go

// Package repository_mock is a generated GoMock package.
package repository_mock

import (
	context "context"
	multipart "mime/multipart"
	reflect "reflect"

	dto "github.com/BangNopall/hology8-be/domain/dto"
	entity "github.com/BangNopall/hology8-be/domain/entity"
	gomock "github.com/golang/mock/gomock"
	uuid "github.com/google/uuid"
	gorm "gorm.io/gorm"
)

// MockTeamRepository is a mock of TeamRepository interface.
type MockTeamRepository struct {
	ctrl     *gomock.Controller
	recorder *MockTeamRepositoryMockRecorder
}

// MockTeamRepositoryMockRecorder is the mock recorder for MockTeamRepository.
type MockTeamRepositoryMockRecorder struct {
	mock *MockTeamRepository
}

// NewMockTeamRepository creates a new mock instance.
func NewMockTeamRepository(ctrl *gomock.Controller) *MockTeamRepository {
	mock := &MockTeamRepository{ctrl: ctrl}
	mock.recorder = &MockTeamRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTeamRepository) EXPECT() *MockTeamRepositoryMockRecorder {
	return m.recorder
}

// Begin mocks base method.
func (m *MockTeamRepository) Begin() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Begin")
	ret0, _ := ret[0].(error)
	return ret0
}

// Begin indicates an expected call of Begin.
func (mr *MockTeamRepositoryMockRecorder) Begin() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Begin", reflect.TypeOf((*MockTeamRepository)(nil).Begin))
}

// Commit mocks base method.
func (m *MockTeamRepository) Commit() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Commit")
	ret0, _ := ret[0].(error)
	return ret0
}

// Commit indicates an expected call of Commit.
func (mr *MockTeamRepositoryMockRecorder) Commit() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Commit", reflect.TypeOf((*MockTeamRepository)(nil).Commit))
}

// Count mocks base method.
func (m *MockTeamRepository) Count(condition string, params []interface{}, groupBy string) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Count", condition, params, groupBy)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Count indicates an expected call of Count.
func (mr *MockTeamRepositoryMockRecorder) Count(condition, params, groupBy interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Count", reflect.TypeOf((*MockTeamRepository)(nil).Count), condition, params, groupBy)
}

// DeleteTeamMember mocks base method.
func (m *MockTeamRepository) DeleteTeamMember(ctx context.Context, member *entity.DetailTeams) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteTeamMember", ctx, member)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteTeamMember indicates an expected call of DeleteTeamMember.
func (mr *MockTeamRepositoryMockRecorder) DeleteTeamMember(ctx, member interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteTeamMember", reflect.TypeOf((*MockTeamRepository)(nil).DeleteTeamMember), ctx, member)
}

// FetchAllByConditionAndRelation mocks base method.
func (m *MockTeamRepository) FetchAllByConditionAndRelation(ctx context.Context, condition string, args []interface{}, order string, pageParam *dto.PaginationRequest, preload ...string) ([]entity.Team, dto.PaginationResponse, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{ctx, condition, args, order, pageParam}
	for _, a := range preload {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "FetchAllByConditionAndRelation", varargs...)
	ret0, _ := ret[0].([]entity.Team)
	ret1, _ := ret[1].(dto.PaginationResponse)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// FetchAllByConditionAndRelation indicates an expected call of FetchAllByConditionAndRelation.
func (mr *MockTeamRepositoryMockRecorder) FetchAllByConditionAndRelation(ctx, condition, args, order, pageParam interface{}, preload ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{ctx, condition, args, order, pageParam}, preload...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FetchAllByConditionAndRelation", reflect.TypeOf((*MockTeamRepository)(nil).FetchAllByConditionAndRelation), varargs...)
}

// FetchAllTeams mocks base method.
func (m *MockTeamRepository) FetchAllTeams(ctx context.Context, params *dto.TeamParams, relations ...string) ([]entity.Team, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{ctx, params}
	for _, a := range relations {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "FetchAllTeams", varargs...)
	ret0, _ := ret[0].([]entity.Team)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FetchAllTeams indicates an expected call of FetchAllTeams.
func (mr *MockTeamRepositoryMockRecorder) FetchAllTeams(ctx, params interface{}, relations ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{ctx, params}, relations...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FetchAllTeams", reflect.TypeOf((*MockTeamRepository)(nil).FetchAllTeams), varargs...)
}

// FetchMemberTeams mocks base method.
func (m *MockTeamRepository) FetchMemberTeams(ctx context.Context, userId uuid.UUID) ([]entity.DetailTeams, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FetchMemberTeams", ctx, userId)
	ret0, _ := ret[0].([]entity.DetailTeams)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FetchMemberTeams indicates an expected call of FetchMemberTeams.
func (mr *MockTeamRepositoryMockRecorder) FetchMemberTeams(ctx, userId interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FetchMemberTeams", reflect.TypeOf((*MockTeamRepository)(nil).FetchMemberTeams), ctx, userId)
}

// FetchOneByID mocks base method.
func (m *MockTeamRepository) FetchOneByID(ctx context.Context, id string) (entity.Team, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FetchOneByID", ctx, id)
	ret0, _ := ret[0].(entity.Team)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FetchOneByID indicates an expected call of FetchOneByID.
func (mr *MockTeamRepositoryMockRecorder) FetchOneByID(ctx, id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FetchOneByID", reflect.TypeOf((*MockTeamRepository)(nil).FetchOneByID), ctx, id)
}

// FetchOneByParams mocks base method.
func (m *MockTeamRepository) FetchOneByParams(ctx context.Context, params *dto.TeamParams, relations ...string) (entity.Team, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{ctx, params}
	for _, a := range relations {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "FetchOneByParams", varargs...)
	ret0, _ := ret[0].(entity.Team)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FetchOneByParams indicates an expected call of FetchOneByParams.
func (mr *MockTeamRepositoryMockRecorder) FetchOneByParams(ctx, params interface{}, relations ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{ctx, params}, relations...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FetchOneByParams", reflect.TypeOf((*MockTeamRepository)(nil).FetchOneByParams), varargs...)
}

// FetchTeamMember mocks base method.
func (m *MockTeamRepository) FetchTeamMember(ctx context.Context, teamId string, userId uuid.UUID) (entity.DetailTeams, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FetchTeamMember", ctx, teamId, userId)
	ret0, _ := ret[0].(entity.DetailTeams)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FetchTeamMember indicates an expected call of FetchTeamMember.
func (mr *MockTeamRepositoryMockRecorder) FetchTeamMember(ctx, teamId, userId interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FetchTeamMember", reflect.TypeOf((*MockTeamRepository)(nil).FetchTeamMember), ctx, teamId, userId)
}

// InsertTeam mocks base method.
func (m *MockTeamRepository) InsertTeam(ctx context.Context, team *entity.Team) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "InsertTeam", ctx, team)
	ret0, _ := ret[0].(error)
	return ret0
}

// InsertTeam indicates an expected call of InsertTeam.
func (mr *MockTeamRepositoryMockRecorder) InsertTeam(ctx, team interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "InsertTeam", reflect.TypeOf((*MockTeamRepository)(nil).InsertTeam), ctx, team)
}

// InsertTeamMember mocks base method.
func (m *MockTeamRepository) InsertTeamMember(ctx context.Context, teamMember *entity.DetailTeams) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "InsertTeamMember", ctx, teamMember)
	ret0, _ := ret[0].(error)
	return ret0
}

// InsertTeamMember indicates an expected call of InsertTeamMember.
func (mr *MockTeamRepositoryMockRecorder) InsertTeamMember(ctx, teamMember interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "InsertTeamMember", reflect.TypeOf((*MockTeamRepository)(nil).InsertTeamMember), ctx, teamMember)
}

// LinkVoucher mocks base method.
func (m *MockTeamRepository) LinkVoucher(ctx context.Context, team *entity.Team, voucher *entity.Voucher, tx *gorm.DB) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "LinkVoucher", ctx, team, voucher, tx)
	ret0, _ := ret[0].(error)
	return ret0
}

// LinkVoucher indicates an expected call of LinkVoucher.
func (mr *MockTeamRepositoryMockRecorder) LinkVoucher(ctx, team, voucher, tx interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "LinkVoucher", reflect.TypeOf((*MockTeamRepository)(nil).LinkVoucher), ctx, team, voucher, tx)
}

// Rollback mocks base method.
func (m *MockTeamRepository) Rollback() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Rollback")
	ret0, _ := ret[0].(error)
	return ret0
}

// Rollback indicates an expected call of Rollback.
func (mr *MockTeamRepositoryMockRecorder) Rollback() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Rollback", reflect.TypeOf((*MockTeamRepository)(nil).Rollback))
}

// UpdateTeam mocks base method.
func (m *MockTeamRepository) UpdateTeam(ctx context.Context, id string, team *dto.TeamUpdate) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateTeam", ctx, id, team)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateTeam indicates an expected call of UpdateTeam.
func (mr *MockTeamRepositoryMockRecorder) UpdateTeam(ctx, id, team interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateTeam", reflect.TypeOf((*MockTeamRepository)(nil).UpdateTeam), ctx, id, team)
}

// MockTeamService is a mock of TeamService interface.
type MockTeamService struct {
	ctrl     *gomock.Controller
	recorder *MockTeamServiceMockRecorder
}

// MockTeamServiceMockRecorder is the mock recorder for MockTeamService.
type MockTeamServiceMockRecorder struct {
	mock *MockTeamService
}

// NewMockTeamService creates a new mock instance.
func NewMockTeamService(ctrl *gomock.Controller) *MockTeamService {
	mock := &MockTeamService{ctrl: ctrl}
	mock.recorder = &MockTeamServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTeamService) EXPECT() *MockTeamServiceMockRecorder {
	return m.recorder
}

// CountTeamNUniv mocks base method.
func (m *MockTeamService) CountTeamNUniv(ctx context.Context) (dto.TeamNUnivCounter, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CountTeamNUniv", ctx)
	ret0, _ := ret[0].(dto.TeamNUnivCounter)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CountTeamNUniv indicates an expected call of CountTeamNUniv.
func (mr *MockTeamServiceMockRecorder) CountTeamNUniv(ctx interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CountTeamNUniv", reflect.TypeOf((*MockTeamService)(nil).CountTeamNUniv), ctx)
}

// CreateTeam mocks base method.
func (m *MockTeamService) CreateTeam(ctx context.Context, leaderID uuid.UUID, team dto.TeamRegister) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateTeam", ctx, leaderID, team)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateTeam indicates an expected call of CreateTeam.
func (mr *MockTeamServiceMockRecorder) CreateTeam(ctx, leaderID, team interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateTeam", reflect.TypeOf((*MockTeamService)(nil).CreateTeam), ctx, leaderID, team)
}

// FetchAll mocks base method.
func (m *MockTeamService) FetchAll(ctx context.Context, params *dto.TeamParams, pageParam *dto.PaginationRequest) (dto.TeamPaginationResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FetchAll", ctx, params, pageParam)
	ret0, _ := ret[0].(dto.TeamPaginationResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FetchAll indicates an expected call of FetchAll.
func (mr *MockTeamServiceMockRecorder) FetchAll(ctx, params, pageParam interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FetchAll", reflect.TypeOf((*MockTeamService)(nil).FetchAll), ctx, params, pageParam)
}

// FetchStatisticData mocks base method.
func (m *MockTeamService) FetchStatisticData() (dto.TeamCounter, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FetchStatisticData")
	ret0, _ := ret[0].(dto.TeamCounter)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FetchStatisticData indicates an expected call of FetchStatisticData.
func (mr *MockTeamServiceMockRecorder) FetchStatisticData() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FetchStatisticData", reflect.TypeOf((*MockTeamService)(nil).FetchStatisticData))
}

// FetchTeamData mocks base method.
func (m *MockTeamService) FetchTeamData(ctx context.Context, teamId string) (dto.TeamResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FetchTeamData", ctx, teamId)
	ret0, _ := ret[0].(dto.TeamResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FetchTeamData indicates an expected call of FetchTeamData.
func (mr *MockTeamServiceMockRecorder) FetchTeamData(ctx, teamId interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FetchTeamData", reflect.TypeOf((*MockTeamService)(nil).FetchTeamData), ctx, teamId)
}

// FetchUserTeams mocks base method.
func (m *MockTeamService) FetchUserTeams(ctx context.Context, userId uuid.UUID) (dto.UserTeamsResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FetchUserTeams", ctx, userId)
	ret0, _ := ret[0].(dto.UserTeamsResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FetchUserTeams indicates an expected call of FetchUserTeams.
func (mr *MockTeamServiceMockRecorder) FetchUserTeams(ctx, userId interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FetchUserTeams", reflect.TypeOf((*MockTeamService)(nil).FetchUserTeams), ctx, userId)
}

// JoinTeam mocks base method.
func (m *MockTeamService) JoinTeam(ctx context.Context, joinToken string, userId uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "JoinTeam", ctx, joinToken, userId)
	ret0, _ := ret[0].(error)
	return ret0
}

// JoinTeam indicates an expected call of JoinTeam.
func (mr *MockTeamServiceMockRecorder) JoinTeam(ctx, joinToken, userId interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "JoinTeam", reflect.TypeOf((*MockTeamService)(nil).JoinTeam), ctx, joinToken, userId)
}

// RemoveMember mocks base method.
func (m *MockTeamService) RemoveMember(ctx context.Context, member *entity.DetailTeams) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RemoveMember", ctx, member)
	ret0, _ := ret[0].(error)
	return ret0
}

// RemoveMember indicates an expected call of RemoveMember.
func (mr *MockTeamServiceMockRecorder) RemoveMember(ctx, member interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RemoveMember", reflect.TypeOf((*MockTeamService)(nil).RemoveMember), ctx, member)
}

// UpdateLeader mocks base method.
func (m *MockTeamService) UpdateLeader(ctx context.Context, teamId string, leaderId uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateLeader", ctx, teamId, leaderId)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateLeader indicates an expected call of UpdateLeader.
func (mr *MockTeamServiceMockRecorder) UpdateLeader(ctx, teamId, leaderId interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateLeader", reflect.TypeOf((*MockTeamService)(nil).UpdateLeader), ctx, teamId, leaderId)
}

// UpdateTeamData mocks base method.
func (m *MockTeamService) UpdateTeamData(ctx context.Context, id string, team *dto.TeamUpdate) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateTeamData", ctx, id, team)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateTeamData indicates an expected call of UpdateTeamData.
func (mr *MockTeamServiceMockRecorder) UpdateTeamData(ctx, id, team interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateTeamData", reflect.TypeOf((*MockTeamService)(nil).UpdateTeamData), ctx, id, team)
}

// UpdateTeamStatus mocks base method.
func (m *MockTeamService) UpdateTeamStatus(ctx context.Context, id string, team *dto.TeamUpdate) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateTeamStatus", ctx, id, team)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateTeamStatus indicates an expected call of UpdateTeamStatus.
func (mr *MockTeamServiceMockRecorder) UpdateTeamStatus(ctx, id, team interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateTeamStatus", reflect.TypeOf((*MockTeamService)(nil).UpdateTeamStatus), ctx, id, team)
}

// UploadPaymentProof mocks base method.
func (m *MockTeamService) UploadPaymentProof(ctx context.Context, id string, paymentFile *multipart.FileHeader) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UploadPaymentProof", ctx, id, paymentFile)
	ret0, _ := ret[0].(error)
	return ret0
}

// UploadPaymentProof indicates an expected call of UploadPaymentProof.
func (mr *MockTeamServiceMockRecorder) UploadPaymentProof(ctx, id, paymentFile interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UploadPaymentProof", reflect.TypeOf((*MockTeamService)(nil).UploadPaymentProof), ctx, id, paymentFile)
}

// UploadTwibbonProof mocks base method.
func (m *MockTeamService) UploadTwibbonProof(ctx context.Context, id string, twibbonFile *multipart.FileHeader) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UploadTwibbonProof", ctx, id, twibbonFile)
	ret0, _ := ret[0].(error)
	return ret0
}

// UploadTwibbonProof indicates an expected call of UploadTwibbonProof.
func (mr *MockTeamServiceMockRecorder) UploadTwibbonProof(ctx, id, twibbonFile interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UploadTwibbonProof", reflect.TypeOf((*MockTeamService)(nil).UploadTwibbonProof), ctx, id, twibbonFile)
}
