// Code generated by MockGen. DO NOT EDIT.
// Source: domain/announcement.go

// Package repository_mock is a generated GoMock package.
package repository_mock

import (
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	"github.com/hology8/hology-be/domain/entity"
)

// MockAnnouncementRepository is a mock of AnnouncementRepository interface.
type MockAnnouncementRepository struct {
	ctrl     *gomock.Controller
	recorder *MockAnnouncementRepositoryMockRecorder
}

// MockAnnouncementRepositoryMockRecorder is the mock recorder for MockAnnouncementRepository.
type MockAnnouncementRepositoryMockRecorder struct {
	mock *MockAnnouncementRepository
}

// NewMockAnnouncementRepository creates a new mock instance.
func NewMockAnnouncementRepository(ctrl *gomock.Controller) *MockAnnouncementRepository {
	mock := &MockAnnouncementRepository{ctrl: ctrl}
	mock.recorder = &MockAnnouncementRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAnnouncementRepository) EXPECT() *MockAnnouncementRepositoryMockRecorder {
	return m.recorder
}

// DeleteAnnouncement mocks base method.
func (m *MockAnnouncementRepository) DeleteAnnouncement(ctx context.Context, id int) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteAnnouncement", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteAnnouncement indicates an expected call of DeleteAnnouncement.
func (mr *MockAnnouncementRepositoryMockRecorder) DeleteAnnouncement(ctx, id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteAnnouncement", reflect.TypeOf((*MockAnnouncementRepository)(nil).DeleteAnnouncement), ctx, id)
}

// FetchAnnouncementByTo mocks base method.
func (m *MockAnnouncementRepository) FetchAnnouncementByTo(ctx context.Context, teamID string, competitionID int) ([]entity.Announcement, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FetchAnnouncementByTo", ctx, teamID, competitionID)
	ret0, _ := ret[0].([]entity.Announcement)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FetchAnnouncementByTo indicates an expected call of FetchAnnouncementByTo.
func (mr *MockAnnouncementRepositoryMockRecorder) FetchAnnouncementByTo(ctx, teamID, competitionID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FetchAnnouncementByTo", reflect.TypeOf((*MockAnnouncementRepository)(nil).FetchAnnouncementByTo), ctx, teamID, competitionID)
}

// InsertAnnouncement mocks base method.
func (m *MockAnnouncementRepository) InsertAnnouncement(ctx context.Context, announcement *entity.Announcement) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "InsertAnnouncement", ctx, announcement)
	ret0, _ := ret[0].(error)
	return ret0
}

// InsertAnnouncement indicates an expected call of InsertAnnouncement.
func (mr *MockAnnouncementRepositoryMockRecorder) InsertAnnouncement(ctx, announcement interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "InsertAnnouncement", reflect.TypeOf((*MockAnnouncementRepository)(nil).InsertAnnouncement), ctx, announcement)
}

// UpdateAnnouncement mocks base method.
func (m *MockAnnouncementRepository) UpdateAnnouncement(ctx context.Context, announcement *entity.Announcement) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateAnnouncement", ctx, announcement)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateAnnouncement indicates an expected call of UpdateAnnouncement.
func (mr *MockAnnouncementRepositoryMockRecorder) UpdateAnnouncement(ctx, announcement interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateAnnouncement", reflect.TypeOf((*MockAnnouncementRepository)(nil).UpdateAnnouncement), ctx, announcement)
}

// MockAnnouncementService is a mock of AnnouncementService interface.
type MockAnnouncementService struct {
	ctrl     *gomock.Controller
	recorder *MockAnnouncementServiceMockRecorder
}

// MockAnnouncementServiceMockRecorder is the mock recorder for MockAnnouncementService.
type MockAnnouncementServiceMockRecorder struct {
	mock *MockAnnouncementService
}

// NewMockAnnouncementService creates a new mock instance.
func NewMockAnnouncementService(ctrl *gomock.Controller) *MockAnnouncementService {
	mock := &MockAnnouncementService{ctrl: ctrl}
	mock.recorder = &MockAnnouncementServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAnnouncementService) EXPECT() *MockAnnouncementServiceMockRecorder {
	return m.recorder
}

// CreateAnnouncement mocks base method.
func (m *MockAnnouncementService) CreateAnnouncement(ctx context.Context, announcement *entity.Announcement) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateAnnouncement", ctx, announcement)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateAnnouncement indicates an expected call of CreateAnnouncement.
func (mr *MockAnnouncementServiceMockRecorder) CreateAnnouncement(ctx, announcement interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateAnnouncement", reflect.TypeOf((*MockAnnouncementService)(nil).CreateAnnouncement), ctx, announcement)
}

// DeleteAnnouncement mocks base method.
func (m *MockAnnouncementService) DeleteAnnouncement(ctx context.Context, id int) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteAnnouncement", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteAnnouncement indicates an expected call of DeleteAnnouncement.
func (mr *MockAnnouncementServiceMockRecorder) DeleteAnnouncement(ctx, id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteAnnouncement", reflect.TypeOf((*MockAnnouncementService)(nil).DeleteAnnouncement), ctx, id)
}

// FetchAnnouncementByTo mocks base method.
func (m *MockAnnouncementService) FetchAnnouncementByTo(ctx context.Context, teamID string, competitionID int) ([]entity.Announcement, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FetchAnnouncementByTo", ctx, teamID, competitionID)
	ret0, _ := ret[0].([]entity.Announcement)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FetchAnnouncementByTo indicates an expected call of FetchAnnouncementByTo.
func (mr *MockAnnouncementServiceMockRecorder) FetchAnnouncementByTo(ctx, teamID, competitionID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FetchAnnouncementByTo", reflect.TypeOf((*MockAnnouncementService)(nil).FetchAnnouncementByTo), ctx, teamID, competitionID)
}

// UpdateAnnouncement mocks base method.
func (m *MockAnnouncementService) UpdateAnnouncement(ctx context.Context, announcement *entity.Announcement) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateAnnouncement", ctx, announcement)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateAnnouncement indicates an expected call of UpdateAnnouncement.
func (mr *MockAnnouncementServiceMockRecorder) UpdateAnnouncement(ctx, announcement interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateAnnouncement", reflect.TypeOf((*MockAnnouncementService)(nil).UpdateAnnouncement), ctx, announcement)
}
